# Generated by scripts/generate-templates.py from the upstream runner-images template.
# Do not edit by hand - change the template's generator.json and regenerate instead.

build {
  sources = ["source.proxmox-iso.ubuntu-slim"]
  name    = "ubuntu-slim"

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:prepare-image-generation] Prepare the image generation workspace'"]
  }

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    inline = [
      "mkdir -p /imagegeneration",
      "chmod 777 /imagegeneration",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:upload-build] Upload build scripts'"]
  }

  provisioner "file" {
    source      = "${local.ubuntu_slim_root}/scripts/build"
    destination = "${local.build_script_folder}"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:upload-helpers] Upload helper scripts'"]
  }

  provisioner "file" {
    source      = "${local.ubuntu_slim_root}/scripts/helpers"
    destination = "${local.helper_script_folder}"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:upload-toolsets] Upload the toolset definitions'"]
  }

  provisioner "file" {
    source      = "${local.ubuntu_slim_root}/toolsets"
    destination = "${local.installer_script_folder}"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:upload-github-api-curl-wrapper] Upload GitHub API curl wrapper'"]
  }

  provisioner "file" {
    source      = "${path.root}/../../../../scripts/github-api-curl-wrapper.sh"
    destination = "/tmp/github-api-curl-wrapper.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-github-api-wrapper] Configure GitHub API rate-limit wrapper'"]
  }

  provisioner "shell" {
    environment_vars = [
      "GH_API_TOKEN=${var.github_api_token}",
      "GH_API_MIN_REMAINING=${var.github_api_min_remaining}",
      "GH_API_WAIT_BUFFER_SECONDS=${var.github_api_wait_buffer_seconds}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    inline = [
      "install -m 0755 /tmp/github-api-curl-wrapper.sh /usr/local/bin/curl",
      "printf 'GITHUB_API_MIN_REMAINING=%s\\nGITHUB_API_WAIT_BUFFER_SECONDS=%s\\n' \"$GH_API_MIN_REMAINING\" \"$GH_API_WAIT_BUFFER_SECONDS\" > /etc/github-api-rate-limit.conf",
      "if [ -n \"$GH_API_TOKEN\" ]; then printf '%s' \"$GH_API_TOKEN\" > /etc/github-api-token; chmod 644 /etc/github-api-token; fi",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-apt-sources] Configure apt sources'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/configure-apt-sources.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-apt] Configure apt'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/configure-apt.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-apt-vital] Install apt vital'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-apt-vital.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-ms-repos] Install Microsoft repos'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-ms-repos.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-image-data-file] Configure image data file'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/configure-image-data-file.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-environment] Configure environment'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/configure-environment.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-actions-cache] Install Actions cache'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-actions-cache.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-apt-common] Install apt common'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-apt-common.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-azcopy] Install AzCopy'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-azcopy.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-azure-cli] Install Azure CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-azure-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-azure-devops-cli] Install Azure DevOps CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-azure-devops-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-bicep] Install Bicep'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-bicep.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-aws-tools] Install AWS tools'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-aws-tools.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-git] Install Git'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-git.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-git-lfs] Install Git LFS'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-git-lfs.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-github-cli] Install GitHub CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-github-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-google-cloud-cli] Install Google cloud CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-google-cloud-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-nvm] Install nvm'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-nvm.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-nodejs] Install Node.js'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-nodejs.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-powershell] Install PowerShell'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-powershell.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-dpkg] Configure dpkg'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/configure-dpkg.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-yq] Install yq'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-yq.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-python] Install Python'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-python.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-zstd] Install zstd'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-zstd.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-pipx-packages] Install pipx packages'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-pipx-packages.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-docker-cli] Install Docker CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/install-docker-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-system] Configure system'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/build/configure-system.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:cleanup] Cleanup'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "IMAGEDATA_NAME=${local.imagedata_name}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_slim_root}/scripts/helpers/cleanup.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-actions-runner] Install the GitHub Actions runner'"]
  }

  provisioner "shell" {
    inline = [
      "set -e",
      "sudo mkdir -p /opt/actions-runner",
      "sudo chown ${var.ssh_username}:${var.ssh_username} /opt/actions-runner",
      "cd /opt/actions-runner",
      "RUNNER_VERSION=$(curl -fsSL https://api.github.com/repos/actions/runner/releases/latest | grep '\"tag_name\"' | head -n1 | sed -E 's/.*\"v([^\"]+)\".*/\\1/')",
      "curl -o actions-runner-linux-x64.tar.gz -L \"https://github.com/actions/runner/releases/download/v$${RUNNER_VERSION}/actions-runner-linux-x64-$${RUNNER_VERSION}.tar.gz\"",
      "tar xzf actions-runner-linux-x64.tar.gz && rm actions-runner-linux-x64.tar.gz",
      "sudo ./bin/installdependencies.sh",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-ssh-public-key] Install SSH public key'"]
  }

  provisioner "shell" {
    environment_vars = ["SSH_PUBLIC_KEY=${var.ssh_public_key}"]
    inline = [
      "set -e",
      "if [ -n \"$SSH_PUBLIC_KEY\" ]; then mkdir -p ~/.ssh && chmod 700 ~/.ssh && printf '%s\\n' \"$SSH_PUBLIC_KEY\" >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys; fi",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:cleanup-template] Cleanup prior to Proxmox template creation'"]
  }

  provisioner "shell" {
    inline = [
      "sudo cloud-init clean",
      "sudo rm -f /etc/ssh/ssh_host_*",
      "sudo truncate -s 0 /etc/machine-id",
    ]
  }
}
