# Generated by scripts/generate-templates.py from the upstream runner-images template.
# Do not edit by hand - change the template's generator.json and regenerate instead.

build {
  sources = ["source.proxmox-iso.ubuntu2404"]
  name    = "ubuntu2404"

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:create-the-image-generation-directory] Create the image generation directory'"]
  }

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    inline = [
      "mkdir ${local.image_folder}",
      "chmod 777 ${local.image_folder}",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:upload-helpers] Upload helper scripts'"]
  }

  provisioner "file" {
    source      = "${local.ubuntu_root}/scripts/helpers"
    destination = "${local.helper_script_folder}"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:upload-github-api-curl-wrapper] Upload GitHub API curl wrapper'"]
  }

  provisioner "file" {
    source      = "${path.root}/../../../../scripts/github-api-curl-wrapper.sh"
    destination = "/tmp/github-api-curl-wrapper.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-github-api-rate-limit-wrapper] Configure GitHub API rate-limit wrapper'"]
  }

  provisioner "shell" {
    environment_vars = [
      "GH_API_TOKEN=${var.github_api_token}",
      "GH_API_MIN_REMAINING=${var.github_api_min_remaining}",
      "GH_API_WAIT_BUFFER_SECONDS=${var.github_api_wait_buffer_seconds}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    inline = [
      "install -m 0755 /tmp/github-api-curl-wrapper.sh /usr/local/bin/curl",
      "printf 'GITHUB_API_MIN_REMAINING=%s\\nGITHUB_API_WAIT_BUFFER_SECONDS=%s\\n' \"$GH_API_MIN_REMAINING\" \"$GH_API_WAIT_BUFFER_SECONDS\" > /etc/github-api-rate-limit.conf",
      "if [ -n \"$GH_API_TOKEN\" ]; then printf '%s' \"$GH_API_TOKEN\" > /etc/github-api-token; chmod 644 /etc/github-api-token; fi",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-apt-mock] Configure the apt mock'"]
  }

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/configure-apt-mock.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-ms-repos] Add Microsoft repos and configure apt sources'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts = [
      "${local.ubuntu_root}/scripts/build/install-ms-repos.sh",
      "${local.ubuntu_root}/scripts/build/configure-apt-sources.sh",
      "${local.ubuntu_root}/scripts/build/configure-apt.sh",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-limits] Configure system limits'"]
  }

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/configure-limits.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:upload-build] Upload installer scripts'"]
  }

  provisioner "file" {
    source      = "${local.ubuntu_root}/scripts/build"
    destination = "${local.installer_script_folder}"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:upload-post-gen] Upload post-gen assets and tests'"]
  }

  provisioner "file" {
    sources = [
      "${local.ubuntu_root}/assets/post-gen",
      "${local.ubuntu_root}/scripts/tests",
    ]
    destination = "${local.image_folder}"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:upload-toolset-2404] Upload the toolset definition'"]
  }

  provisioner "file" {
    source      = "${local.ubuntu_root}/toolsets/toolset-2404.json"
    destination = "${local.installer_script_folder}/toolset.json"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:rename-post-gen-to-post-generation] Rename post-gen to post-generation'"]
  }

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    inline          = ["mv ${local.image_folder}/post-gen ${local.image_folder}/post-generation"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-image-data] Write the image data file'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "IMAGE_VERSION=${local.image_version}",
      "IMAGEDATA_FILE=${local.imagedata_file}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts         = ["${local.ubuntu_root}/scripts/build/configure-image-data.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:stub-waagent-conf] Stub waagent.conf for the upstream environment script'"]
  }

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    inline = [
      "touch /etc/waagent.conf",
      "grep -q ResourceDisk.Format /etc/waagent.conf || echo 'ResourceDisk.Format=n' >> /etc/waagent.conf",
      "grep -q ResourceDisk.EnableSwap /etc/waagent.conf || echo 'ResourceDisk.EnableSwap=n' >> /etc/waagent.conf",
      "grep -q ResourceDisk.SwapSizeMB /etc/waagent.conf || echo 'ResourceDisk.SwapSizeMB=0' >> /etc/waagent.conf",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-environment] Configure the image environment'"]
  }

  provisioner "shell" {
    environment_vars = [
      "IMAGE_VERSION=${local.image_version}",
      "IMAGE_OS=${local.image_os}",
      "HELPER_SCRIPTS=${local.helper_script_folder}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts         = ["${local.ubuntu_root}/scripts/build/configure-environment.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-apt-vital] Install vital apt packages'"]
  }

  provisioner "shell" {
    environment_vars = [
      "DEBIAN_FRONTEND=noninteractive",
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts         = ["${local.ubuntu_root}/scripts/build/install-apt-vital.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-powershell] Install PowerShell'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts         = ["${local.ubuntu_root}/scripts/build/install-powershell.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:Install-PowerShellModules] Install PowerShell and Azure modules'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} pwsh -f {{ .Path }}'"
    scripts = [
      "${local.ubuntu_root}/scripts/build/Install-PowerShellModules.ps1",
      "${local.ubuntu_root}/scripts/build/Install-PowerShellAzModules.ps1",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-actions-cache] Install Actions cache'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-actions-cache.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-apt-common] Install apt common'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-apt-common.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-azcopy] Install AzCopy'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-azcopy.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-azure-cli] Install Azure CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-azure-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-azure-devops-cli] Install Azure DevOps CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-azure-devops-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-bicep] Install Bicep'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-bicep.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-apache] Install Apache'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-apache.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-aws-tools] Install AWS tools'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-aws-tools.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-clang] Install Clang'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-clang.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-swift] Install Swift'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-swift.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-cmake] Install CMake'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-cmake.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-codeql-bundle] Install CodeQL bundle'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-codeql-bundle.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-awf] Install AWF'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-awf.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-container-tools] Install container tools'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-container-tools.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-dotnetcore-sdk] Install .NET Core SDK'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-dotnetcore-sdk.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-microsoft-edge] Install Microsoft Edge'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-microsoft-edge.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-gcc-compilers] Install GCC compilers'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-gcc-compilers.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-firefox] Install Firefox'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-firefox.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-gfortran] Install GFortran'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-gfortran.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-git] Install Git'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-git.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-git-lfs] Install Git LFS'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-git-lfs.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-github-cli] Install GitHub CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-github-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-google-chrome] Install Google Chrome'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-google-chrome.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-google-cloud-cli] Install Google cloud CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-google-cloud-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-haskell] Install Haskell'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-haskell.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-java-tools] Install Java tools'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-java-tools.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-kubernetes-tools] Install Kubernetes tools'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-kubernetes-tools.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-miniconda] Install Miniconda'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-miniconda.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-kotlin] Install Kotlin'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-kotlin.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-mysql] Install MySQL'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-mysql.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-nginx] Install nginx'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-nginx.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-nvm] Install nvm'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-nvm.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-nodejs] Install Node.js'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-nodejs.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-copilot-cli] Install Copilot CLI'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-copilot-cli.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-bazel] Install Bazel'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-bazel.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-php] Install PHP'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-php.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-postgresql] Install PostgreSQL'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-postgresql.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-pulumi] Install Pulumi'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-pulumi.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-ruby] Install Ruby'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-ruby.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-rust] Install Rust'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-rust.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-julia] Install Julia'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-julia.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-selenium] Install Selenium'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-selenium.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-packer] Install Packer'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-packer.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-vcpkg] Install vcpkg'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-vcpkg.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-dpkg] Configure dpkg'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/configure-dpkg.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-yq] Install yq'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-yq.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-android-sdk] Install Android SDK'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-android-sdk.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-pypy] Install PyPy'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-pypy.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-python] Install Python'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-python.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-zstd] Install zstd'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-zstd.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-ninja] Install Ninja'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/install-ninja.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-docker] Install Docker'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts         = ["${local.ubuntu_root}/scripts/build/install-docker.sh"]
  }

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    inline          = ["usermod -aG docker ${var.ssh_username}"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:Install-Toolset] Install and configure the hosted toolcache'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} pwsh -f {{ .Path }}'"
    scripts = [
      "${local.ubuntu_root}/scripts/build/Install-Toolset.ps1",
      "${local.ubuntu_root}/scripts/build/Configure-Toolset.ps1",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-pipx-packages] Install pipx packages'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts         = ["${local.ubuntu_root}/scripts/build/install-pipx-packages.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-homebrew] Install Homebrew'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPTS=${local.helper_script_folder}",
      "DEBIAN_FRONTEND=noninteractive",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
    ]
    execute_command = "/bin/sh -c '{{ .Vars }} {{ .Path }}'"
    scripts         = ["${local.ubuntu_root}/scripts/build/install-homebrew.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-snap] Configure snap'"]
  }

  provisioner "shell" {
    environment_vars = ["HELPER_SCRIPTS=${local.helper_script_folder}"]
    execute_command  = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts          = ["${local.ubuntu_root}/scripts/build/configure-snap.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:list-dpkg] Record the installed dpkg package list'"]
  }

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "${local.ubuntu_root}/scripts/build/list-dpkg.sh"
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:reboot-the-vm] Reboot the VM'"]
  }

  provisioner "shell" {
    execute_command   = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    expect_disconnect = true
    inline = [
      "echo 'Reboot VM'",
      "sudo reboot",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:cleanup] Cleanup after the reboot'"]
  }

  provisioner "shell" {
    execute_command     = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    pause_before        = "5m0s"
    start_retry_timeout = "10m"
    scripts             = ["${local.ubuntu_root}/scripts/build/cleanup.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:configure-system] Configure the system'"]
  }

  provisioner "shell" {
    environment_vars = [
      "HELPER_SCRIPT_FOLDER=${local.helper_script_folder}",
      "INSTALLER_SCRIPT_FOLDER=${local.installer_script_folder}",
      "IMAGE_FOLDER=${local.image_folder}",
    ]
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts         = ["${local.ubuntu_root}/scripts/build/configure-system.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:post-build-validation] Post-build validation'"]
  }

  provisioner "shell" {
    environment_vars = ["HELPER_SCRIPTS=${local.helper_script_folder}"]
    execute_command  = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    scripts          = ["${local.ubuntu_root}/scripts/build/post-build-validation.sh"]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:download-the-actions-runner] Download the GitHub Actions runner'"]
  }

  provisioner "shell" {
    inline = [
      "set -e",
      "sudo mkdir -p /opt/actions-runner",
      "sudo chown ${var.ssh_username}:${var.ssh_username} /opt/actions-runner",
      "cd /opt/actions-runner",
      "RUNNER_VERSION=$(curl -fsSL https://api.github.com/repos/actions/runner/releases/latest | grep '\"tag_name\"' | head -n1 | sed -E 's/.*\"v([^\"]+)\".*/\\1/')",
      "curl -o actions-runner-linux-x64.tar.gz -L \"https://github.com/actions/runner/releases/download/v$${RUNNER_VERSION}/actions-runner-linux-x64-$${RUNNER_VERSION}.tar.gz\"",
      "tar xzf actions-runner-linux-x64.tar.gz && rm actions-runner-linux-x64.tar.gz",
      "sudo ./bin/installdependencies.sh",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:install-ssh-public-key] Install SSH public key'"]
  }

  provisioner "shell" {
    environment_vars = ["SSH_PUBLIC_KEY=${var.ssh_public_key}"]
    inline = [
      "set -e",
      "if [ -n \"$SSH_PUBLIC_KEY\" ]; then mkdir -p ~/.ssh && chmod 700 ~/.ssh && printf '%s\\n' \"$SSH_PUBLIC_KEY\" >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys; fi",
    ]
  }

  provisioner "shell-local" {
    inline = ["echo '[image-builder:stage:cleanup-for-template-creation] Cleanup prior to Proxmox template creation'"]
  }

  provisioner "shell" {
    inline = [
      "sudo cloud-init clean --logs --seed",
      "sudo rm -f /etc/ssh/ssh_host_*",
      "sudo rm -rf /var/lib/dhcp/* /var/lib/systemd/network /var/lib/NetworkManager/*.lease*",
      "sudo truncate -s 0 /etc/machine-id",
      "sudo rm -f /var/lib/dbus/machine-id",
      "sudo ln -s /etc/machine-id /var/lib/dbus/machine-id",
    ]
  }
}
